const express = require('express')
const router =  express.Router()
const {createUserWithPasspost,createUser,login,addToWishList,getWishList} = require('../controller/userCtrl')
const { authMiddleware } = require('../config/authMiddlware')
router.post(`/registre`,createUser)
router.post(`/login`,login)
router.post(`/createGoogleUser`,createUserWithPasspost)
router.put('/addWidhList',authMiddleware,addToWishList)
router.get('/wishListGet',authMiddleware,getWishList)
module.exports = router